apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: glusterpvc
 annotations:
   volume.beta.kubernetes.io/storage-class: slow
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 2Gi 
