apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: default
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
  key: "aGZXcWRJeFVJYXo4a09YTXZkNFhDRlpqWnl3bXdueTdhcWtLY3E0MnFmMD0="
type: kubernetes.io/glusterfs

